POST http://localhost:4000/course/ HTTP/1.1
content-type: application/json


{
    "name": "Fundamental Programming Practices",
    "code": "CS390",
    "blockEntry": {
        "year": 2021,
        "month": 5
    },
    "faculty": "Obinna Kalu",
    "capacity": 34,
    "enrolled": 28,
    "description": "Fundamentals of OO Programming"
}

###
